### ISSUE TITLE
g:gdbmi#auto_mapping undefined

### ISSUE THREAD

**Issue by jkunlin** [skt041959/gdbmi.nvim#2]
Is there any doc to show the usage?

**Comment by skt041959** [comment]
@jkunlin There isn't much doc about this project. 
Thank you for your test and report. Recently, I don't have much time to fix these issues. I'm so sorry.

**Comment by skt041959** [comment]
The code is much refactored. There is no g:gdbmi#auto_mapping now. Hance close this.
